/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'comp_accrued_adjusted_5ce616a2' })
export class CompAccruedAdjustedEntity_5ce616a2 extends BlockchainEventEntity {
  @Column({
    name: 'user',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public user: string; // address

  @Column({
    name: 'old_comp_accrued',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public oldCompAccrued: string; // uint

  @Column({
    name: 'new_comp_accrued',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public newCompAccrued: string; // uint
}
