/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'comp_borrow_speed_updated_6a38bf23' })
export class CompBorrowSpeedUpdatedEntity_6a38bf23 extends BlockchainEventEntity {
  @Column({
    name: 'c_token',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public cToken: string; // address

  @Column({
    name: 'new_speed',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public newSpeed: string; // uint
}
