/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'distributed_borrower_comp_8bcf5026' })
export class DistributedBorrowerCompEntity_8bcf5026 extends BlockchainEventEntity {
  @Column({
    name: 'c_token',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public cToken: string; // address

  @Column({
    name: 'borrower',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public borrower: string; // address

  @Column({
    name: 'comp_delta',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public compDelta: string; // uint

  @Column({
    name: 'comp_borrow_index',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public compBorrowIndex: string; // uint
}
