/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'new_borrow_cap_guardian_e7776ba7' })
export class NewBorrowCapGuardianEntity_e7776ba7 extends BlockchainEventEntity {
  @Column({
    name: 'old_borrow_cap_guardian',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public oldBorrowCapGuardian: string; // address

  @Column({
    name: 'new_borrow_cap_guardian',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public newBorrowCapGuardian: string; // address
}
