/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'new_close_factor_187cb1f6' })
export class NewCloseFactorEntity_187cb1f6 extends BlockchainEventEntity {
  @Column({
    name: 'old_close_factor_mantissa',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public oldCloseFactorMantissa: string; // uint

  @Column({
    name: 'new_close_factor_mantissa',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public newCloseFactorMantissa: string; // uint
}
