/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'new_liquidation_incentive_0f450502' })
export class NewLiquidationIncentiveEntity_0f450502 extends BlockchainEventEntity {
  @Column({
    name: 'old_liquidation_incentive_mantissa',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public oldLiquidationIncentiveMantissa: string; // uint

  @Column({
    name: 'new_liquidation_incentive_mantissa',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public newLiquidationIncentiveMantissa: string; // uint
}
