/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'new_pause_guardian_a15b5c9d' })
export class NewPauseGuardianEntity_a15b5c9d extends BlockchainEventEntity {
  @Column({
    name: 'old_pause_guardian',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public oldPauseGuardian: string; // address

  @Column({
    name: 'new_pause_guardian',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public newPauseGuardian: string; // address
}
