/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import {
  Column,
  Entity,
  JoinColumn,
  OneToMany,
  ManyToOne,
  OneToOne,
  PrimaryGeneratedColumn,
  DeleteDateColumn,
  Index,
} from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'transfer_fab013d9' })
export class TransferEntity_fab013d9 extends BlockchainEventEntity {
  @Column({
    name: 'from',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public from: string; // address

  @Column({
    name: 'to',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public to: string; // address

  @Column({
    name: 'amount',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public amount: string; // uint
}
