/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'counter_decremented_f4b3f987' })
export class CounterDecrementedEntity_f4b3f987 extends BlockchainEventEntity {
  @Column({
    name: 'new_count',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public newCount: string; // uint
}
