{
 "title": "Indexer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_number" }
   ]
  },
  {
   "title": "Latest Indexed Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "latest_indexed_block_number" }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "block_number - latest_indexed_block_number"
    }
   ]
  },
  {
   "title": "Last Indexed Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_indexed_block_timestamp * 1000"
    }
   ]
  },
  {
   "title": "Indexed Blocks (2m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "increase(indexed_blocks[2m])" }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "increase(reorgs[2m])" }
   ]
  },
  {
   "title": "Indexed Logs per Block",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(logs_count_per_block_bucket[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block Processing Time Distribution (ms)",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(block_process_iteration_duration_bucket[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}