/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_439e6b8c } from './TheStructEntity_439e6b8c';

import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import * as constants from '../constants';

@Entity({ name: 'dynamic_array_439e6b8c' })
export class DynamicArrayEntity_439e6b8c {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @Column({
    name: 'dynamic_array',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public dynamicArray: string; // uint

  @ManyToOne(
    () => TheStructEntity_439e6b8c,
    (theStruct: TheStructEntity_439e6b8c) => theStruct.dynamicArray,
  )
  public theStruct: TheStructEntity_439e6b8c;
}
