/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_439e6b8c } from './TheStructEntity_439e6b8c';

import { Entity, JoinColumn, OneToOne } from 'typeorm';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'event_with_struct_with_arrays_439e6b8c' })
export class EventWithStructWithArraysEntity_439e6b8c extends BlockchainEventEntity {
  @OneToOne(
    () => TheStructEntity_439e6b8c,
    (theStruct: TheStructEntity_439e6b8c) =>
      theStruct.eventWithStructWithArrays,
    {
      eager: true,
      cascade: true,
    },
  )
  @JoinColumn()
  public theStruct: TheStructEntity_439e6b8c; // tuple
}
