/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { EventWithFixedArrayEntity_696b4daf } from './EventWithFixedArrayEntity_696b4daf';

import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import * as constants from '../constants';

@Entity({ name: 'uint64_array_696b4daf' })
export class Uint64ArrayEntity_696b4daf {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @Column({
    name: 'uint64_array',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public uint64Array: string; // uint

  @ManyToOne(
    () => EventWithFixedArrayEntity_696b4daf,
    (eventWithFixedArray: EventWithFixedArrayEntity_696b4daf) =>
      eventWithFixedArray.uint64Array,
  )
  public eventWithFixedArray: EventWithFixedArrayEntity_696b4daf;
}
