/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { EventWithDynamicArrayEntity_e56f559a } from './EventWithDynamicArrayEntity_e56f559a';

import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import * as constants from '../constants';

@Entity({ name: 'dynamic_array_e56f559a' })
export class DynamicArrayEntity_e56f559a {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @Column({
    name: 'dynamic_array',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public dynamicArray: string; // uint

  @ManyToOne(
    () => EventWithDynamicArrayEntity_e56f559a,
    (eventWithDynamicArray: EventWithDynamicArrayEntity_e56f559a) =>
      eventWithDynamicArray.dynamicArray,
  )
  public eventWithDynamicArray: EventWithDynamicArrayEntity_e56f559a;
}
