/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_de916601 } from './TheStructEntity_de916601';

import { Entity, JoinColumn, OneToOne } from 'typeorm';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'event_with_struct_with_dynamic_struct_array_de916601' })
export class EventWithStructWithDynamicStructArrayEntity_de916601 extends BlockchainEventEntity {
  @OneToOne(
    () => TheStructEntity_de916601,
    (theStruct: TheStructEntity_de916601) =>
      theStruct.eventWithStructWithDynamicStructArray,
    {
      eager: true,
      cascade: true,
    },
  )
  @JoinColumn()
  public theStruct: TheStructEntity_de916601; // tuple
}
