/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { Uint64ArrayEntity_696b4daf } from './Uint64ArrayEntity_696b4daf';

import { Entity, JoinColumn, OneToMany } from 'typeorm';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'event_with_fixed_array_696b4daf' })
export class EventWithFixedArrayEntity_696b4daf extends BlockchainEventEntity {
  @OneToMany(
    () => Uint64ArrayEntity_696b4daf,
    (uint64Array: Uint64ArrayEntity_696b4daf) =>
      uint64Array.eventWithFixedArray,
    {
      eager: true,
      cascade: true,
    },
  )
  @JoinColumn()
  public uint64Array: Uint64ArrayEntity_696b4daf[]; // uint64[3]
}
