/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_4ec25295 } from './TheStructEntity_4ec25295';

import { Entity, JoinColumn, OneToOne } from 'typeorm';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'event_with_struct_with_nested_struct_4ec25295' })
export class EventWithStructWithNestedStructEntity_4ec25295 extends BlockchainEventEntity {
  @OneToOne(
    () => TheStructEntity_4ec25295,
    (theStruct: TheStructEntity_4ec25295) =>
      theStruct.eventWithStructWithNestedStruct,
    {
      eager: true,
      cascade: true,
    },
  )
  @JoinColumn()
  public theStruct: TheStructEntity_4ec25295; // tuple
}
