/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */

import { Column, Entity } from 'typeorm';
import * as constants from '../constants';
import { BlockchainEventEntity } from './BlockchainEventEntity';

@Entity({ name: 'simple_event_f9536490' })
export class SimpleEventEntity_f9536490 extends BlockchainEventEntity {
  @Column({
    name: 'num64_value',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_64_MAX_DIGITS,
    update: false,
  })
  public num64Value: string; // uint

  @Column({
    name: 'bool_value',
    nullable: false,
    type: 'boolean',
    update: false,
  })
  public boolValue: boolean; // bool

  @Column({
    name: 'string_value',
    nullable: false,
    type: 'varchar',
    update: false,
  })
  public stringValue: string; // string

  @Column({
    name: 'addr_value',
    nullable: false,
    type: 'varchar',
    update: false,
    length: constants.BYTES_32_LENGTH,
  })
  public addrValue: string; // address

  @Column({
    name: 'bytes1_value',
    nullable: false,
    type: 'varchar',
    update: false,
  })
  public bytes1Value: string; // bytes

  @Column({
    name: 'bytes32_value',
    nullable: false,
    type: 'varchar',
    update: false,
  })
  public bytes32Value: string; // bytes

  @Column({
    name: 'int256_value',
    nullable: false,
    type: 'numeric',
    precision: constants.INT_256_MAX_DIGITS,
    update: false,
  })
  public int256Value: string; // int

  @Column({
    name: 'int64_value',
    nullable: false,
    type: 'numeric',
    precision: constants.INT_64_MAX_DIGITS,
    update: false,
  })
  public int64Value: string; // int

  @Column({
    name: 'some_enum',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_8_MAX_DIGITS,
    update: false,
  })
  public someEnum: string; // uint
}
