/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_4ec25295 } from './TheStructEntity_4ec25295';

import { Column, Entity, OneToOne, PrimaryGeneratedColumn } from 'typeorm';
import * as constants from '../constants';

@Entity({ name: 'simple_struct_4ec25295' })
export class SimpleStructEntity_4ec25295 {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @Column({
    name: 'a',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public a: string; // uint

  @Column({
    name: 'b',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public b: string; // uint

  @OneToOne(
    () => TheStructEntity_4ec25295,
    (theStruct: TheStructEntity_4ec25295) => theStruct.simpleStruct,
  )
  public theStruct: TheStructEntity_4ec25295;
}
