/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { TheStructEntity_68e489fd } from './TheStructEntity_68e489fd';

import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import * as constants from '../constants';

@Entity({ name: 'struct_array_68e489fd' })
export class StructArrayEntity_68e489fd {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @Column({
    name: 'a',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public a: string; // uint

  @Column({
    name: 'b',
    nullable: false,
    type: 'numeric',
    precision: constants.UINT_256_MAX_DIGITS,
    update: false,
  })
  public b: string; // uint

  @ManyToOne(
    () => TheStructEntity_68e489fd,
    (theStruct: TheStructEntity_68e489fd) => theStruct.structArray,
  )
  public theStruct: TheStructEntity_68e489fd;
}
