/* --------------------------------------------------------------------- *\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\* ---------------------------------------------------------------------  */
import { SimpleStructEntity_4ec25295 } from './SimpleStructEntity_4ec25295';
import { EventWithStructWithNestedStructEntity_4ec25295 } from './EventWithStructWithNestedStructEntity_4ec25295';

import { Entity, JoinColumn, OneToOne, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'the_struct_4ec25295' })
export class TheStructEntity_4ec25295 {
  @PrimaryGeneratedColumn('increment')
  public id: string;

  @OneToOne(
    () => SimpleStructEntity_4ec25295,
    (simpleStruct: SimpleStructEntity_4ec25295) => simpleStruct.theStruct,
    {
      eager: true,
      cascade: true,
    },
  )
  @JoinColumn()
  public simpleStruct: SimpleStructEntity_4ec25295; // tuple

  @OneToOne(
    () => EventWithStructWithNestedStructEntity_4ec25295,
    (
      eventWithStructWithNestedStruct: EventWithStructWithNestedStructEntity_4ec25295,
    ) => eventWithStructWithNestedStruct.theStruct,
  )
  public eventWithStructWithNestedStruct: EventWithStructWithNestedStructEntity_4ec25295;
}
